### PR TITLE
Enhanced documentation

### PR DESCRIPTION
**Pull request by sanikaahadap**
Fixed the typos and added content for a better understanding. Kindly review the changes. 
1) Fixed the spelling mistakes for 'scrape' and it's various forms
2) Enhanced the introduction by elaborating on it

### CODE REVIEW

**Comment by sanikaahadap** [comment]
Also removed an extra '.git' extension in the clone command.

**Comment by sanikaahadap** [comment]
I have made the necessary changes in the readme file, sir. Are there any more changes required?

**Review by sanjay-kv — APPROVED** [review]
Good to go, you can merge it by yourself. Thanks for contributing.

**Comment by sanikaahadap** [comment]
Sir, I can't merge it, as I don't have the write access.

**Pull request merged**
