### PR TITLE
 Add Streamlit web app for IMDb movie review analysis and recommendations

### PR DESCRIPTION
**Pull request by revanth1718**
Developed Streamlit app for uploading CSV files, performing sentiment analysis, and displaying recommendations

## Related Issue
Streamlit Webapp

## Description
This pull request introduces a Streamlit web application designed for analyzing IMDb movie reviews and providing recommendations based on sentiment analysis. The app enables users to upload a CSV file containing movie reviews, perform sentiment analysis using a Support Vector Machine (SVM) classifier, and display the results along with top movie recommendations based on positive reviews.

## Type of PR

- [X] Feature enhancement

## Screenshots / videos (if applicable)

https://github.com/Recode-Hive/Scrape-ML/assets/109272714/7d0c4818-62c3-49a0-bb27-6b626a625356

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
The Streamlit app provides a user-friendly interface for movie review analysis and includes error handling for unsupported file encodings. Debug prints are included to help trace data flow and ensure the correct operation of sentiment analysis and recommendation features.

I'm participating in GSSoC'24 (GirlScript Summer of Code 2024)

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]

**Comment by sanjay-kv** [comment]
Can you connect with me on linkedin: I have future ideas to discuss on streamlit https://www.linkedin.com/in/sanjay-k-v/

**Comment by revanth1718** [comment]
ok sir, i have sent you a connection request
https://www.linkedin.com/in/revanth1/

**Comment by sanjay-kv** [comment]
can you make a documentation inside the folder to show how to run the website, also would you be able to host this in github pages?

**Comment by revanth1718** [comment]
sir, it is not possible to deploy a Streamlit app directly on GitHub Pages. To deploy a Streamlit app, you need to use a service that supports dynamic applications. Some popular options include: Streamlit Community Cloud (formerly Streamlit Sharing),Heroku.

**Comment by revanth1718** [comment]
We can host a streamlit app through Streamlit Community Cloud as it is free of cost by connecting with the github account. We should connect the main github account where the actual repo consists of to the Streamlit Community Cloud account.

**Comment by sanjay-kv** [comment]
yes i have made the account and connected the repo. let me know further steps, if we can connect gmeet 1:1 call. that would be better 
image

**Comment by revanth1718** [comment]
sir, could you share the gmeet link and time , i will join the meeting.

**Comment by sanjay-kv** [comment]
Sure we can connect today 8:00pm IST? could  you leave me the email ID I will sent you invitation to join meet.

**Comment by revanth1718** [comment]
ok sir, my email id: revanthpasupuleti18@gmail.com

**Pull request merged**
