### PR TITLE
fixed the issue in scrapping.py 

### PR DESCRIPTION
**Pull request by kairveeehh**
#14  fixed the issue with relevant comments as well 
### please review and merge the PR 
-thankyou 
kairveeehh

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]
Approved , Thanks

**Comment by kairveeehh** [comment]
@sanjay-kv please attach levels to both the PRs so that they can be counted in the leaderboard @sanjay-kv

**Comment by sanjay-kv** [comment]
its a minor issue cant add level to these . sorry about that.

**Comment by kairveeehh** [comment]
> its a minor issue cant add level to these . sorry about that.

then you should not assign it and say that before hand , what about the other one??? @sanjay-kv

**Comment by sanjay-kv** [comment]
@kairveeehh It has been communicated well before via documentation and via email, documentation with high changes only given level1. all links changes will be added gssoc

**Pull request merged**
