### PR TITLE
Create Decision Tree Classifier

### PR DESCRIPTION
**Pull request by IqraMiyaji**
It can create a Decision tree which can help one to find the hierarchy  most important feature

## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [x] Feature enhancement

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
why different file. the main idea is to enhance existing file. Kindly look into it.

**Comment by IqraMiyaji** [comment]
Good evening sir
Sorry sir actually it was my first PR
I will correct it soon..

**Comment by IqraMiyaji** [comment]
Sorry, sir, but I cannot understand...
Can you please explain.

**Comment by sanjay-kv** [comment]
https://github.com/Recode-Hive/machine-learning-repos here you can raise the issue, as it complete beginner friendly

**Comment by IqraMiyaji** [comment]
Thanks a lot.

**Pull request closed without merging**
