### PR TITLE
Clustering movie summaries added

### PR DESCRIPTION
**Pull request by merciajeno**
## Related Issue
https://github.com/Recode-Hive/Scrape-ML/issues/64

## Description
1.We scrape IMDb data including movie titles, ratings, and summaries using BeautifulSoup
2.We use TF-IDF vectorization to convert the movie summaries into numerical feature vectors.
3.We apply K-means clustering to group the movies into clusters based on their summaries.
4.We use PCA for dimensionality reduction to visualize the clusters in a 2D space.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image
image
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

Co-authored-by: I Mercia Jeno [mercia.jeno@gmail.com](mailto:mercia.jeno@gmail.com)
Co-authored-by:  Bhakti Kalyankasture [kalyankasturebhakti@gmail.com](mailto:kalyankasturebhakti@gmail.com)

### CODE REVIEW

**Comment by merciajeno** [comment]
@sanjay-kv , can you review the code and tell whether we need to make some changes?

**Review by sanjay-kv — APPROVED** [review]

**Comment by sanjay-kv** [comment]
I reviewed all good, can you tell this person to comment here: Bhakti Kalyankasture [kalyankasturebhakti@gmail.com](mailto:kalyankasturebhakti@gmail.com) otherwise I wont be able to assign the issue.

**Comment by Roverbk** [comment]
@sanjay-kv

**Comment by sanjay-kv** [comment]
To make badge visible https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

need to follow this steps while committing. you can still reopen the request or do it. i will merge

**Pull request merged**
