### PR TITLE
Update scrapping.py

### PR DESCRIPTION
**Pull request by Harshitmishra001**
## Related Issue
Updating amazon_scrapping /scrapping.py for imporvements
Issue #180 

## Description
**Key Improvements:**

1. Ensures elements are loaded before interacting with them.
2. Correctly handles the pagination and breaks the loop when there are no more pages.
3. Uses the correct XPATH and class names.
4. Creates a DataFrame with a column name and saves it correctly.

## Type of PR

- [ ] Bug fix
- [✅ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Screenshot 2024-06-08 113151
Screenshot 2024-06-08 113201

## Checklist:
- [ ✅] I have performed a self-review of my code
- [ ✅] I have read and followed the Contribution Guidelines.
- [ ✅] I have tested the changes thoroughly before submitting this pull request.
- [ ✅] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ✅] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by sanjay-kv** [comment]
i need to run and test, give me a day of time. or today eve

**Comment by Harshitmishra001** [comment]
No problem ,
when I was done writing the code I actually forgot to create a issue for it earlier that's why my PR was early😅

**Comment by sanjay-kv** [comment]
image


could you help fixing this.

**Comment by Harshitmishra001** [comment]
Hi I'm sure I can try to 😄

**Comment by sanjay-kv** [comment]
@Harshitmishra001 i need one help with simillar repo. would you like to connect on gmeet for the same.

**Comment by Harshitmishra001** [comment]
@sanjay-kv Sure we can do it tomorrow whenever you are available😄

**Comment by sanjay-kv** [comment]
okay. could you please send me a linkedin request. will take it from there.

**Comment by Harshitmishra001** [comment]
@sanjay-kv Hi, We are already connected on Linkedin 
 My linkedin ID - https://www.linkedin.com/in/harshit-mishra-98329128a/
 email id - hmharsh123@gmail.com

**Pull request merged**
