### PR TITLE
Collaborate

### PR DESCRIPTION
**Pull request by merciajeno**
## Related Issue
https://github.com/Recode-Hive/Scrape-ML/pull/108

## Description
Two people i.e- I Mercia Jeno and Bhakti  Kalyankasture have collaborated to the issue https://github.com/Recode-Hive/Scrape-ML/issues/64, that has been merged already.

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [x] Other (specify):Collaboration by two people on same issue

### CODE REVIEW

**Comment by merciajeno** [comment]
@sanjay-kv ,I have followed the steps mentioned in https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by sanjay-kv** [comment]
image
yes now i can see that. Thanks 

can you document the steps one by one in the next pull request with screenshot. 
I will send you this ebook for free https://learn.recodehive.com/datascience

**Comment by sanjay-kv** [comment]
+ Let me know when github badge available on your profile.

**Comment by sanjay-kv** [comment]
@Roverbk i was not able to assign you. can you comment or edit any comments . then I can assign u as well

**Comment by merciajeno** [comment]
@sanjay-kv , I have received the badge

**Pull request merged**
