### PR TITLE
Update README.md [Redesign README Image]

### PR DESCRIPTION
**Pull request by me-shweta**
## Description
I have replaced the picture with the updated one.

## Screenshots / videos (if applicable)
Capture

## Additional context:
@sanjay-kv "Try to merge the code without review."

### CODE REVIEW

**Comment by me-shweta** [comment]
Closes: #109

**Comment by me-shweta** [comment]
@sanjay-kv Sorry for the inconvenience, but I did not receive the YOLO badge.

**Comment by sanjay-kv** [comment]
It takes times, GitHub will verify and takes around 2 days

**Comment by me-shweta** [comment]
okay.. Glad to hear that.

**Pull request merged**
