### PR TITLE
added dependency file

### PR DESCRIPTION
**Pull request by revanth1718**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]

**Comment by sanjay-kv** [comment]
There will be one invitation mail on your email to join organisation, can you accept it?

**Comment by revanth1718** [comment]
Sir, you do the same deploy process.

**Comment by revanth1718** [comment]
sir can you gmeet now. so we can deploy our app now.

**Comment by sanjay-kv** [comment]
https://scrape-review-analysis.streamlit.app/

**Comment by revanth1718** [comment]
i am happy that our app deployed. sir ,can you please tell what should i do to accept the request
Screenshot (543)

**Pull request merged**
