### PR TITLE
 Enhance Streamlit app with Lottie animation and HTML styling [Issue resolve #148]

### LINKED ISSUE #148: Enhance Streamlit app with Lottie animation and HTML styling
The IMDb Movie Review Analysis and Recommendation System Streamlit app could benefit from enhancements to improve user engagement and visual appeal. This issue proposes adding a Lottie animation and implementing HTML styling to achieve these objectives.

### Proposed Changes:
Integrate a Lottie animation into the app using the streamlit_lottie library to create a more dynamic and engaging user experience.
Enhance the HTML styling of the app, including the title, upload section, and error messages, to improve aesthetics and usability.

### Expected Benefits:
Increased user engagement: The addition of a Lottie animation will make the app more visually appealing and interactive, encouraging users to explore its features.
Enhanced aesthetics: HTML styling improvements will result in a more polished and professional appearance, contributing to a positive user experience.
Additional Notes:

It's essential to ensure that the Lottie animation and HTML styling are implemented in a way that maintains the app's accessibility and responsiveness across different devices and screen sizes.
Testing will be necessary to verify that the enhancements function correctly and do not introduce any regressions in app functionality.

Please assign this issue to me under Gssoc.

### PR DESCRIPTION
**Pull request by SurajSanap**
Issue resolve #148 

This pull request enhances the IMDb Movie Review Analysis and Recommendation System Streamlit app by adding a Lottie animation and improving the HTML styling for a better user experience.

Changes Made:

Added a Lottie animation to the app using the streamlit_lottie library to make the interface more dynamic and engaging.
Implemented HTML styling for the title, upload section, and error messages to maintain a consistent and polished look throughout the app.
Reason for Changes:

The addition of a Lottie animation adds visual interest and interactivity to the app, making it more engaging for users.
HTML styling improves the overall aesthetics of the app, providing a more professional and polished appearance.
Testing Done:

Tested the app locally to ensure that the Lottie animation is displayed correctly and the HTML styling is applied as expected.
Verified that the app functions properly across different browsers and screen sizes.

Screenshots:
2024-05-30 21-26-26 (online-video-cutter com)

Screenshot 2024-05-30 212703

### CODE REVIEW

**Comment by sanjay-kv** [comment]
could you contact me on the linkedin I have more PR for you

**Comment by sanjay-kv** [comment]
Kindly fix the conflicts

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
Conflcits issue

**Comment by SurajSanap** [comment]
I need to rebuild it.

**Pull request closed without merging**
